zuul:
  ignored-services: '*'
  routes:
    bookmarks: '/**'
  sensitive-headers:

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  application:
    name: 'reverseproxy'
